### PR TITLE
fixes for lossy algorithm

### PR DESCRIPTION
**Pull request by seeforschauer**
http://www.vldb.org/conf/2002/S10P03.pdf

### CODE REVIEW

**Comment by shanemhansen** [comment]
@lename Thanks for your helping out! I don't have a formal contribution process for this, but I just added a BSD license to the code. If that's OK, I'll go ahead and merge.

**Comment by seeforschauer** [comment]
@shanemhansen , thank you for fast answer.
I assume here is also could be sync for the map. So as soon as I implement the better version, I make a better pull request.

**Comment by shanemhansen** [comment]
@lename I'm definitely open to the idea of a goroutine safe version, but before introducing sync overhead for all users of the lib I'd like to make sure that a "native" goroutine safe version performs better than a version that just wraps a `countish.Counter` with a sync.Mutex or sync.RWMutex.

**Comment by seeforschauer** [comment]
I'll close and enroll a new one request with correct commit and a good message in it.

**Pull request closed without merging**
